name: 'Smoke test'
inputs:
  template:
    description: 'Template to test'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout master
      id: checkout_release
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Build template
      id: build_template
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.template }}
