name: "CI - Test Templates"
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            azure-functions-dotnet: ./**/azure-functions-dotnet/**
            azure-functions-go: ./**/azure-functions-go/**
            azure-functions-java: ./**/azure-functions-java/**
            azure-functions-node: ./**/azure-functions-node/**
            azure-functions-powershell: ./**/azure-functions-powershell/**
            azure-functions-python: ./**/azure-functions-python/**

  test:
    needs: [detect-changes]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
